#!/usr/bin/env bash
# bail if something falls over
set -e

NAME="$1.git"
DESTINATION="/opt/git"
cd $DESTINATION

# create the repo
git init --bare --shared --quiet $NAME

# give some useful feedback
SERVER="eggbasket"
REPO_PATH="git@$SERVER:$DESTINATION/$NAME"
echo "$REPO_PATH"
